[package]
name = "globed-central-server"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globed-shared = { path = "../shared" }

async-watcher = "0.2.0"
blake2 = "0.10.6"
digest = "0.10.7"
ipnet = "2.9.0"
iprange = "0.6.7"
serde = { version = "1.0.197", features = ["serde_derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
totp-rs = "5.5.1"
json_comments = "0.2.2"
rocket = "0.5.0"
rocket_db_pools = { version = "0.1.0", features = ["sqlx_sqlite"] }
sqlx = { version = "0.7.3", features = ["migrate"] }
rocket_ws = "0.1.0"
